name: Bench PR

on:
  pull_request:
    types: [ opened, synchronize ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: tcheinen/iai-compare-action@main