name: Rust

on:
  push:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Deserialize CTF test case
      run: cargo run --manifest-path test-harness/Cargo.toml --bin ctf
    - name: Deserialize no_subcommands test case
      run: cargo run --manifest-path test-harness/Cargo.toml --bin no_subcommands
    - name: Deserialize multiple_schema test case
      run: cargo run --manifest-path test-harness/Cargo.toml --bin multiple_schema
  benchmark:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Valgrind
        run: sudo apt-get install -y valgrind
      - name: Bench
        run: cargo bench
      - uses: actions/upload-artifact@v2
        with:
          name: iai
          path: lib/target/iai/cachegrind.out*
